### ISSUE TITLE
Please port the extension to Firefox

### ISSUE THREAD

**Issue by adamency** [bytebase/star-history#94] opened 2021-09-23 01:03 UTC
This software is extremely important and I humbly thank you for it.

That said, it is however in dire need of a Firefox extension, which is the only major browser bringing competition opposite the chromium monopoly. Please don't be a contributor to this situation and help bring back variety to the landscape of our modern internet tools by offering an extension there too.

Thanks again, with the hope that this message will bear its fruits :).

**Comment by timqian** [comment] 2021-09-23 04:39
Thanks, Benjamin I will try to publish it to Firefox when I got time

**Comment by tianzhou** [comment] 2021-12-01 11:02
Duplicate of #89

**Closed by tianzhou** 2021-12-01 11:02 UTC
